name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: download
        run: |
          git config --local user.email "haannn@qq.com"
          git config --local user.name "Han Han"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
          git pull --rebase
          pip3 install youtube-dl
          ./start.sh
          git add .
          git commit -m "download youtube video(s)"
          git push
